apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: trino-block
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: trino-pv
spec:
   capacity:
     storage: 80Gi
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: trino-block
   local:
     path: /mnt/trino
   nodeAffinity:
     required:
       nodeSelectorTerms:
       - matchExpressions:
         - key: kubernetes.io/hostname
           operator: In
           values:
           - node-01
           - node-02

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: trino-pv-claim
spec:
   storageClassName: trino-block
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 80Gi
