all:
  hosts:
    master-1:
      ansible_host: 192.168.56.117
      ip: 192.168.56.117
      access_ip: 192.168.56.117
    worker-1:
      ansible_host: 192.168.56.116
      ip: 192.168.56.116
      access_ip: 192.168.56.116
    worker-2:
      ansible_host: 192.168.56.118
      ip: 192.168.56.118
      access_ip: 192.168.56.118
  children:
    kube_control_plane:
      hosts:
        master-1:
    kube_node:
      hosts:
        master-1:
        worker-1:
        worker-2:
    etcd:
      hosts:
        master-1:
        worker-1:
        worker-2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
