all:
  hosts:
    node1:
      ansible_host: 192.168.56.117
      ip: 192.168.56.117
      access_ip: 192.168.56.117
    node2:
      ansible_host: 192.168.56.116
      ip: 192.168.56.116
      access_ip: 192.168.56.116
    node3:
      ansible_host: 192.168.56.118
      ip: 192.168.56.118
      access_ip: 192.168.56.118
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
