all:
  hosts:
    node1:
      ansible_host: 192.168.18.8
      ip: 192.168.18.8
      access_ip: 192.168.18.8
    node2:
      ansible_host: 192.168.18.11
      ip: 192.168.18.11
      access_ip: 192.168.18.11
    node3:
      ansible_host: 192.168.18.5
      ip: 192.168.18.5
      access_ip: 192.168.18.5
    node4:
      ansible_host: 192.168.18.21
      ip: 192.168.18.21
      access_ip: 192.168.18.21
    node5:
      ansible_host: 192.168.18.2
      ip: 192.168.18.2
      access_ip: 192.168.18.2
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
