all:
  hosts:
    master-1:
      ansible_host: 10.20.20.30
      ip: 10.20.20.30
      access_ip: 10.20.20.30
    worker-1:
      ansible_host: 10.20.20.31
      ip: 10.20.20.31
      access_ip: 10.20.20.31
    worker-2:
      ansible_host: 10.20.20.32
      ip: 10.20.20.32
      access_ip: 10.20.20.32
    
  children:
    kube-master:
      hosts:
        master-1:
    kube-node:
      hosts:
        master-1:
        worker-1:
        worker-2:
    etcd:
      hosts:
        master-1:
        worker-1:
        worker-2:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
